# VPM Repository Configuration
# このファイルで対象のリポジトリとオーナーを設定します

# デフォルトのリポジトリオーナー
default_owner: "your-github-username"

# 管理対象のリポジトリリスト
repositories:
  - name: "your-package-1"
    owner: "package-owner"  # 異なる場合のみ指定
  - name: "your-package-2"

# VPMリポジトリの設定
vpm_settings:
  repo_url: "https://your-username.github.io/your-repo-name/vpm.json"
  name: "Your VPM Repository"
  description: "あなたのVRChat用パッケージリポジトリ"
  author_name: "your-username"
  author_url: "https://github.com/your-username"