name: Update Repository Options
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/config/repositories.yml'

jobs:
  update-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Install js-yaml
        run: npm install js-yaml

      - name: Get Repository Options
        id: GetOptions
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const mod = await import("${{ github.workspace }}/.github/workflows/JsScripts/GetRepositoryOptions.mjs");
            const repositories = mod.getRepositoryOptions();
            return repositories.join('\n          - ');

      - name: Update Workflow File
        env:
          REPO_OPTIONS: ${{ steps.GetOptions.outputs.result }}
        run: |
          # AddNewVersion.ymlファイルのオプション部分を更新
          # この処理は手動で行うか、より高度なスクリプトで実装可能
          echo "利用可能なリポジトリ:"
          echo "$REPO_OPTIONS"
          echo "手動でAddNewVersion.ymlのoptionsセクションを更新してください"
