name: Update Repository Configuration
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/config/repositories.yml'

jobs:
  update-configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          npm install js-yaml
          pip install pyyaml

      - name: Get Repository Options
        id: GetOptions
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const mod = await import("${{ github.workspace }}/.github/workflows/JsScripts/GetRepositoryOptions.mjs");
            const repositories = mod.getRepositoryOptions();
            return repositories.join('\n          - ');

      - name: Update AddNewVersion.yml
        env:
          REPO_OPTIONS: ${{ steps.GetOptions.outputs.result }}
        run: |
          # Python script to update the workflow file
          python3 << 'EOF'
          import re
          import sys
          
          # Read the workflow file
          with open('.github/workflows/AddNewVersion.yml', 'r') as f:
              content = f.read()
          
          # Get the new options from environment
          new_options = "${{ steps.GetOptions.outputs.result }}"
          formatted_options = "          - " + new_options.replace('\n          - ', '\n          - ')
          
          # Replace the options section
          pattern = r'(options:\s*\n)((?:\s*-\s*[^\n]+\n?)*)'
          replacement = f'\\1{formatted_options}\n'
          
          updated_content = re.sub(pattern, replacement, content)
          
          # Write back the file
          with open('.github/workflows/AddNewVersion.yml', 'w') as f:
              f.write(updated_content)
          
          print("AddNewVersion.yml has been updated successfully!")
          EOF

      - name: Update add-repo.html
        id: UpdateAddRepoHtml
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const mod = await import("${{ github.workspace }}/.github/workflows/JsScripts/UpdateAddRepoHtml.mjs");
            const result = mod.updateAddRepoHtml();
            return JSON.stringify(result);

      - name: Display Updated URLs
        env:
          UPDATE_RESULT: ${{ steps.UpdateAddRepoHtml.outputs.result }}
        run: |
          echo "=== add-repo.html Update Result ==="
          echo "$UPDATE_RESULT" | python3 -m json.tool
          echo ""

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/workflows/AddNewVersion.yml add-repo.html
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update workflow options and add-repo.html from repositories.yml"
            git push origin
          fi
